# Generated by Django 3.2.8 on 2025-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
