# Generated by Django 3.2.8 on 2025-02-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch_id',
        ),
    ]
