# Generated by Django 3.2.8 on 2025-02-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
