# Generated by Django 3.2.8 on 2025-02-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attendance_attendance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='Present', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session_year'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='attendance_report',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
